FORMAT: 1A
HOST: http://savantory.apiblueprint.org/

# Savantory

Savantory is a set of APIs that help people discover great books and have a community.

# Group Books

## Books [/api/books]

### List all of my Books [GET]

Get the list of all the books that I am either reading, read and need to read.

+ Response 200

        [
            {
                "_id": 2,
                "referenceId": 3234,
                "name": "Node: Up and Running",
                "author": [
                    "Mike Wilson",
                    "Tom Hughes-Croucher"
                ]
            },
            {
                "_id": 3,
                "referenceId": 3235,
                "name": "Node: Up and Running 2nd edition",
                "author": [
                  "Mike Wilson",
                  "Tom Hughes-Croucher"
                ]
            }
        ]
        