FORMAT: 1A
HOST: http://savantory.apiblueprint.org/

# Savantory

Savantory is a set of APIs that help people discover great books and have a community.

# Group Books

## Books [/books]

### List all of my Books [GET]

Get the list of all the books that I am either reading, read and need to read.

+ Response 200 (application/json)

        [
            {
                "id": 2,
                "referenceId": 3234,
                "name": "Node: Up and Running",
                "author": [
                    "Mike Wilson",
                    "Tom Hughes-Croucher"
                ]
            }
        ]
        
+ Response 500 (application/json)

        {
            "error": "Internal Server Error",
            "description": "Something went wrong in the computation"
        }

### Add a Book to my list [POST]

Adding a book that I searched for and selected to add to my list of books.

+ Request (application/json)

        {
            "name": "Node: Up and Running",
            "author": [
                "Mike Wilson",
                "Tom Hughes-Croucher"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /books/2

    + Body

            {
                "id": 2,
                "referenceId": 3234,
                "name": "Node: Up and Running",
                "author": [
                    "Mike Wilson",
                    "Tom Hughes-Croucher"
                ]
            }
            
## Specific Book [/books/{id}]

### Retrieve a specific book [GET]

Get the list of all the books that I am either reading, read and need to read.

+ Parameters
    + id (number, required) - Id of the book

+ Response 200 (application/json)

        {
            "id": 2,
            "referenceId": 3234,
            "name": "Node: Up and Running",
            "author": [
                "Mike Wilson",
                "Tom Hughes-Croucher"
            ]
        }
            
# Group Social
